# Generated by Django 4.2.7 on 2024-07-17 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pedido_pedidoproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='identificador',
            field=models.IntegerField(verbose_name='Identificador da Sacola'),
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_sacola', models.IntegerField(verbose_name='Quantidade Sacola')),
                ('data_de_entrega', models.DateField(verbose_name='Data de Entrega')),
                ('data_de_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('sacola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sacola', to='app.pedido')),
            ],
        ),
    ]
